//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""Quest"",
            ""id"": ""dadda380-308a-4881-b64b-13b5f33023d9"",
            ""actions"": [
                {
                    ""name"": ""GripLeft"",
                    ""type"": ""Button"",
                    ""id"": ""a8c46698-c9af-4e52-8c7a-f513e1c0a2bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripRight"",
                    ""type"": ""Button"",
                    ""id"": ""f6c03567-2ac0-434d-9a05-2a137072256f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerLeft"",
                    ""type"": ""Button"",
                    ""id"": ""279bd800-44cc-4421-baff-a6d0b10b1b1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerRight"",
                    ""type"": ""Button"",
                    ""id"": ""7f2a63c0-23d0-460d-bca1-ec5bb4123859"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""f2520f33-3173-471e-b7cd-b979fa4c2dd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a8de2b70-e0c6-4082-8526-6d446be1ae55"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92900879-bb95-43f6-8c0a-1e92b9183ff4"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff83f44a-4ad5-4db3-8f90-2882a257315a"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05c65751-5b11-4429-9fda-eec29a191c70"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e125ecc8-b6fb-4243-8fde-c8f25dcd64a0"",
                    ""path"": ""<XRController>{LeftHand}/start"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Quest
        m_Quest = asset.FindActionMap("Quest", throwIfNotFound: true);
        m_Quest_GripLeft = m_Quest.FindAction("GripLeft", throwIfNotFound: true);
        m_Quest_GripRight = m_Quest.FindAction("GripRight", throwIfNotFound: true);
        m_Quest_TriggerLeft = m_Quest.FindAction("TriggerLeft", throwIfNotFound: true);
        m_Quest_TriggerRight = m_Quest.FindAction("TriggerRight", throwIfNotFound: true);
        m_Quest_Menu = m_Quest.FindAction("Menu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Quest
    private readonly InputActionMap m_Quest;
    private IQuestActions m_QuestActionsCallbackInterface;
    private readonly InputAction m_Quest_GripLeft;
    private readonly InputAction m_Quest_GripRight;
    private readonly InputAction m_Quest_TriggerLeft;
    private readonly InputAction m_Quest_TriggerRight;
    private readonly InputAction m_Quest_Menu;
    public struct QuestActions
    {
        private @NewControls m_Wrapper;
        public QuestActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @GripLeft => m_Wrapper.m_Quest_GripLeft;
        public InputAction @GripRight => m_Wrapper.m_Quest_GripRight;
        public InputAction @TriggerLeft => m_Wrapper.m_Quest_TriggerLeft;
        public InputAction @TriggerRight => m_Wrapper.m_Quest_TriggerRight;
        public InputAction @Menu => m_Wrapper.m_Quest_Menu;
        public InputActionMap Get() { return m_Wrapper.m_Quest; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(QuestActions set) { return set.Get(); }
        public void SetCallbacks(IQuestActions instance)
        {
            if (m_Wrapper.m_QuestActionsCallbackInterface != null)
            {
                @GripLeft.started -= m_Wrapper.m_QuestActionsCallbackInterface.OnGripLeft;
                @GripLeft.performed -= m_Wrapper.m_QuestActionsCallbackInterface.OnGripLeft;
                @GripLeft.canceled -= m_Wrapper.m_QuestActionsCallbackInterface.OnGripLeft;
                @GripRight.started -= m_Wrapper.m_QuestActionsCallbackInterface.OnGripRight;
                @GripRight.performed -= m_Wrapper.m_QuestActionsCallbackInterface.OnGripRight;
                @GripRight.canceled -= m_Wrapper.m_QuestActionsCallbackInterface.OnGripRight;
                @TriggerLeft.started -= m_Wrapper.m_QuestActionsCallbackInterface.OnTriggerLeft;
                @TriggerLeft.performed -= m_Wrapper.m_QuestActionsCallbackInterface.OnTriggerLeft;
                @TriggerLeft.canceled -= m_Wrapper.m_QuestActionsCallbackInterface.OnTriggerLeft;
                @TriggerRight.started -= m_Wrapper.m_QuestActionsCallbackInterface.OnTriggerRight;
                @TriggerRight.performed -= m_Wrapper.m_QuestActionsCallbackInterface.OnTriggerRight;
                @TriggerRight.canceled -= m_Wrapper.m_QuestActionsCallbackInterface.OnTriggerRight;
                @Menu.started -= m_Wrapper.m_QuestActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_QuestActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_QuestActionsCallbackInterface.OnMenu;
            }
            m_Wrapper.m_QuestActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GripLeft.started += instance.OnGripLeft;
                @GripLeft.performed += instance.OnGripLeft;
                @GripLeft.canceled += instance.OnGripLeft;
                @GripRight.started += instance.OnGripRight;
                @GripRight.performed += instance.OnGripRight;
                @GripRight.canceled += instance.OnGripRight;
                @TriggerLeft.started += instance.OnTriggerLeft;
                @TriggerLeft.performed += instance.OnTriggerLeft;
                @TriggerLeft.canceled += instance.OnTriggerLeft;
                @TriggerRight.started += instance.OnTriggerRight;
                @TriggerRight.performed += instance.OnTriggerRight;
                @TriggerRight.canceled += instance.OnTriggerRight;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
            }
        }
    }
    public QuestActions @Quest => new QuestActions(this);
    public interface IQuestActions
    {
        void OnGripLeft(InputAction.CallbackContext context);
        void OnGripRight(InputAction.CallbackContext context);
        void OnTriggerLeft(InputAction.CallbackContext context);
        void OnTriggerRight(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
    }
}
